server:
  port: 10010


spring:
  profiles:
    # Activate your database configuration
    # The local `db-local`
    # The online `db-online`
    active: mvc, db, db-local
  messages:
    encoding: UTF-8


