
spring:
  datasource:
    druid:
      url:  jdbc:mysql://118.31.45.131:3306/j2ee?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
      username:  j2ee
      password:  123456
