
spring:
  thymeleaf:
    mode: HTML
    suffix: .html
    cache: false
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB