package com.j2ee.db.dao;

import com.j2ee.db.domain.DocumentType;
import com.j2ee.db.domain.DocumentTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DocumentTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_type
     *
     * @mbg.generated
     */
    long countByExample(DocumentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_type
     *
     * @mbg.generated
     */
    int deleteByExample(DocumentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_type
     *
     * @mbg.generated
     */
    int insert(DocumentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_type
     *
     * @mbg.generated
     */
    int insertSelective(DocumentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_type
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DocumentType selectOneByExample(DocumentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_type
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DocumentType selectOneByExampleSelective(@Param("example") DocumentTypeExample example, @Param("selective") DocumentType.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_type
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<DocumentType> selectByExampleSelective(@Param("example") DocumentTypeExample example, @Param("selective") DocumentType.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_type
     *
     * @mbg.generated
     */
    List<DocumentType> selectByExample(DocumentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_type
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DocumentType selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DocumentType.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_type
     *
     * @mbg.generated
     */
    DocumentType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_type
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DocumentType record, @Param("example") DocumentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_type
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DocumentType record, @Param("example") DocumentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DocumentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DocumentType record);
}