package com.j2ee.db.dao;

import com.j2ee.db.domain.TbTest;
import com.j2ee.db.domain.TbTestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbg.generated
     */
    long countByExample(TbTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbg.generated
     */
    int deleteByExample(TbTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbg.generated
     */
    int insert(TbTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbg.generated
     */
    int insertSelective(TbTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TbTest selectOneByExample(TbTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TbTest selectOneByExampleSelective(@Param("example") TbTestExample example, @Param("selective") TbTest.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<TbTest> selectByExampleSelective(@Param("example") TbTestExample example, @Param("selective") TbTest.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbg.generated
     */
    List<TbTest> selectByExample(TbTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TbTest selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TbTest.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbg.generated
     */
    TbTest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbTest record, @Param("example") TbTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbTest record, @Param("example") TbTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbTest record);
}