spring:
  profiles:
    active: core, db
  messages:
    encoding: UTF-8
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /statics/**

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    com.goodstuff.mall.core:  DEBUG