package com.j2ee.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class StuTeaCh {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_tea_ch.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_tea_ch.teacher_id
     *
     * @mbg.generated
     */
    private Integer teacherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_tea_ch.student_id
     *
     * @mbg.generated
     */
    private Integer studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_tea_ch.adviser_info
     *
     * @mbg.generated
     */
    private Integer adviserInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_tea_ch.semester_id
     *
     * @mbg.generated
     */
    private Integer semesterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_tea_ch.appraise_id
     *
     * @mbg.generated
     */
    private Integer appraiseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_tea_ch.intro
     *
     * @mbg.generated
     */
    private String intro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_tea_ch.suggestion
     *
     * @mbg.generated
     */
    private String suggestion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_tea_ch.score
     *
     * @mbg.generated
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_tea_ch.document_id
     *
     * @mbg.generated
     */
    private Integer documentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_tea_ch.is_accept
     *
     * @mbg.generated
     */
    private Byte isAccept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_tea_ch.is_del
     *
     * @mbg.generated
     */
    private Boolean isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_tea_ch.add_time
     *
     * @mbg.generated
     */
    private LocalDateTime addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_tea_ch.id
     *
     * @return the value of stu_tea_ch.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_tea_ch.id
     *
     * @param id the value for stu_tea_ch.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_tea_ch.teacher_id
     *
     * @return the value of stu_tea_ch.teacher_id
     *
     * @mbg.generated
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_tea_ch.teacher_id
     *
     * @param teacherId the value for stu_tea_ch.teacher_id
     *
     * @mbg.generated
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_tea_ch.student_id
     *
     * @return the value of stu_tea_ch.student_id
     *
     * @mbg.generated
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_tea_ch.student_id
     *
     * @param studentId the value for stu_tea_ch.student_id
     *
     * @mbg.generated
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_tea_ch.adviser_info
     *
     * @return the value of stu_tea_ch.adviser_info
     *
     * @mbg.generated
     */
    public Integer getAdviserInfo() {
        return adviserInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_tea_ch.adviser_info
     *
     * @param adviserInfo the value for stu_tea_ch.adviser_info
     *
     * @mbg.generated
     */
    public void setAdviserInfo(Integer adviserInfo) {
        this.adviserInfo = adviserInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_tea_ch.semester_id
     *
     * @return the value of stu_tea_ch.semester_id
     *
     * @mbg.generated
     */
    public Integer getSemesterId() {
        return semesterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_tea_ch.semester_id
     *
     * @param semesterId the value for stu_tea_ch.semester_id
     *
     * @mbg.generated
     */
    public void setSemesterId(Integer semesterId) {
        this.semesterId = semesterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_tea_ch.appraise_id
     *
     * @return the value of stu_tea_ch.appraise_id
     *
     * @mbg.generated
     */
    public Integer getAppraiseId() {
        return appraiseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_tea_ch.appraise_id
     *
     * @param appraiseId the value for stu_tea_ch.appraise_id
     *
     * @mbg.generated
     */
    public void setAppraiseId(Integer appraiseId) {
        this.appraiseId = appraiseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_tea_ch.intro
     *
     * @return the value of stu_tea_ch.intro
     *
     * @mbg.generated
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_tea_ch.intro
     *
     * @param intro the value for stu_tea_ch.intro
     *
     * @mbg.generated
     */
    public void setIntro(String intro) {
        this.intro = intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_tea_ch.suggestion
     *
     * @return the value of stu_tea_ch.suggestion
     *
     * @mbg.generated
     */
    public String getSuggestion() {
        return suggestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_tea_ch.suggestion
     *
     * @param suggestion the value for stu_tea_ch.suggestion
     *
     * @mbg.generated
     */
    public void setSuggestion(String suggestion) {
        this.suggestion = suggestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_tea_ch.score
     *
     * @return the value of stu_tea_ch.score
     *
     * @mbg.generated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_tea_ch.score
     *
     * @param score the value for stu_tea_ch.score
     *
     * @mbg.generated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_tea_ch.document_id
     *
     * @return the value of stu_tea_ch.document_id
     *
     * @mbg.generated
     */
    public Integer getDocumentId() {
        return documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_tea_ch.document_id
     *
     * @param documentId the value for stu_tea_ch.document_id
     *
     * @mbg.generated
     */
    public void setDocumentId(Integer documentId) {
        this.documentId = documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_tea_ch.is_accept
     *
     * @return the value of stu_tea_ch.is_accept
     *
     * @mbg.generated
     */
    public Byte getIsAccept() {
        return isAccept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_tea_ch.is_accept
     *
     * @param isAccept the value for stu_tea_ch.is_accept
     *
     * @mbg.generated
     */
    public void setIsAccept(Byte isAccept) {
        this.isAccept = isAccept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_tea_ch.is_del
     *
     * @return the value of stu_tea_ch.is_del
     *
     * @mbg.generated
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_tea_ch.is_del
     *
     * @param isDel the value for stu_tea_ch.is_del
     *
     * @mbg.generated
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_tea_ch.add_time
     *
     * @return the value of stu_tea_ch.add_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_tea_ch.add_time
     *
     * @param addTime the value for stu_tea_ch.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_tea_ch
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", teacherId=").append(teacherId);
        sb.append(", studentId=").append(studentId);
        sb.append(", adviserInfo=").append(adviserInfo);
        sb.append(", semesterId=").append(semesterId);
        sb.append(", appraiseId=").append(appraiseId);
        sb.append(", intro=").append(intro);
        sb.append(", suggestion=").append(suggestion);
        sb.append(", score=").append(score);
        sb.append(", documentId=").append(documentId);
        sb.append(", isAccept=").append(isAccept);
        sb.append(", isDel=").append(isDel);
        sb.append(", addTime=").append(addTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_tea_ch
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        StuTeaCh other = (StuTeaCh) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTeacherId() == null ? other.getTeacherId() == null : this.getTeacherId().equals(other.getTeacherId()))
            && (this.getStudentId() == null ? other.getStudentId() == null : this.getStudentId().equals(other.getStudentId()))
            && (this.getAdviserInfo() == null ? other.getAdviserInfo() == null : this.getAdviserInfo().equals(other.getAdviserInfo()))
            && (this.getSemesterId() == null ? other.getSemesterId() == null : this.getSemesterId().equals(other.getSemesterId()))
            && (this.getAppraiseId() == null ? other.getAppraiseId() == null : this.getAppraiseId().equals(other.getAppraiseId()))
            && (this.getIntro() == null ? other.getIntro() == null : this.getIntro().equals(other.getIntro()))
            && (this.getSuggestion() == null ? other.getSuggestion() == null : this.getSuggestion().equals(other.getSuggestion()))
            && (this.getScore() == null ? other.getScore() == null : this.getScore().equals(other.getScore()))
            && (this.getDocumentId() == null ? other.getDocumentId() == null : this.getDocumentId().equals(other.getDocumentId()))
            && (this.getIsAccept() == null ? other.getIsAccept() == null : this.getIsAccept().equals(other.getIsAccept()))
            && (this.getIsDel() == null ? other.getIsDel() == null : this.getIsDel().equals(other.getIsDel()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_tea_ch
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTeacherId() == null) ? 0 : getTeacherId().hashCode());
        result = prime * result + ((getStudentId() == null) ? 0 : getStudentId().hashCode());
        result = prime * result + ((getAdviserInfo() == null) ? 0 : getAdviserInfo().hashCode());
        result = prime * result + ((getSemesterId() == null) ? 0 : getSemesterId().hashCode());
        result = prime * result + ((getAppraiseId() == null) ? 0 : getAppraiseId().hashCode());
        result = prime * result + ((getIntro() == null) ? 0 : getIntro().hashCode());
        result = prime * result + ((getSuggestion() == null) ? 0 : getSuggestion().hashCode());
        result = prime * result + ((getScore() == null) ? 0 : getScore().hashCode());
        result = prime * result + ((getDocumentId() == null) ? 0 : getDocumentId().hashCode());
        result = prime * result + ((getIsAccept() == null) ? 0 : getIsAccept().hashCode());
        result = prime * result + ((getIsDel() == null) ? 0 : getIsDel().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table stu_tea_ch
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        teacherId("teacher_id", "teacherId", "INTEGER", false),
        studentId("student_id", "studentId", "INTEGER", false),
        adviserInfo("adviser_info", "adviserInfo", "INTEGER", false),
        semesterId("semester_id", "semesterId", "INTEGER", false),
        appraiseId("appraise_id", "appraiseId", "INTEGER", false),
        intro("intro", "intro", "VARCHAR", false),
        suggestion("suggestion", "suggestion", "VARCHAR", false),
        score("score", "score", "INTEGER", false),
        documentId("document_id", "documentId", "INTEGER", false),
        isAccept("is_accept", "isAccept", "TINYINT", false),
        isDel("is_del", "isDel", "BIT", false),
        addTime("add_time", "addTime", "TIMESTAMP", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table stu_tea_ch
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table stu_tea_ch
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table stu_tea_ch
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table stu_tea_ch
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table stu_tea_ch
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table stu_tea_ch
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table stu_tea_ch
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table stu_tea_ch
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table stu_tea_ch
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table stu_tea_ch
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table stu_tea_ch
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table stu_tea_ch
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table stu_tea_ch
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table stu_tea_ch
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table stu_tea_ch
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}